Velocity aware meshes
SeisSol/PUMGen pull request #33
Opened 2021-09-03 10:17 UTC by krenzland

This draft (!) PR adds the capability of of meshing in a velocity-aware manner.
You can have a look at the example XML file, especially the line
`<velocityAwareMeshing frequency="10" elementsPerWaveLength="2">easiFile.yaml</velocityAwareMeshing>`
This tries to resolve the p-wave with a frequency of 10 Hz using 2 elements per wave length.

Draft PR because 1) CI fails 2) it's not tested properly (but works on a toy example) 3) last day before vacation.

So, feel free to play around with this!

2021-09-03 11:23 UTC, Thomas-Ulrich commented
Cool! Nice effort and code!
- I did not check in detail yet, but I think it would make sense (given we do not have efficient absorbing boundaries) to have the option to limit the attribute to a given region or to a given box shape region.
 (e.g. use 2Hz accurate within the box and 5 km outside).
- it should be based on S-wave, not P-wave.

2021-09-03 14:37 UTC, krenzland commented
Yup, I agree.
Actually, I did choose the p-wave on purpose just because the s-wave speed in the acoustic layer is zero - maybe we can add some way to target certain waves?

About the region: I agree in principle but we'd have to find a smart way of doing it. In simmetrix, I can only give a size function for the entire mesh. Maybe we could add some decay to global mesh size option? I.e. we set the mesh size in a box from the wave length and outside the box we increase the mesh width to the global one?
I actually don't really know how simmetrix handles refinement, if it can consider multiple options (e.g. our function, and a global mesh size) and just takes the minimal size this would be easier. Couldn't find this info in the documentation though.

2022-01-31 15:46 UTC, Thomas-Ulrich requested changes
Looks good, see proposed changes.

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +  std::cout << "Destructor of EasiMeshSize called" << std::endl;
remove debug statement

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +  std::cout << "EasiMeshSize() called" << std::endl;
remove debug statement

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +  std::cout << "EasiMeshSize(easiFileName) called" << std::endl;
remove debug statement

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +    // Note: Does not work on discrete regions!
what is a discrete region?

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/SimModSuite.h
> +      MS_setMeshSize(meshCase, GM_domain(model), MS_userDefinedType | 2, 0, "setCustomMeshSize");
We need type=1:
```
type = 1 | MS_userDefinedType for absolute, type = 2 | MS_userDefinedType for relative user defined size).```

2022-01-31 15:46 UTC, Thomas-Ulrich commented on src/input/SimModSuite.h
> +      // set the user-defined function for anisotropic size
isotropic

2022-01-31 15:47 UTC, Thomas-Ulrich commented on src/input/SimModSuite.h
> +      MS_setMeshSize(meshCase, GM_domain(model), MS_userDefinedType | 2, 0, "setCustomMeshSize");
I must add that I tested it on a real case study and it did not generate a mesh after 30min, probably because of this type 2.

2022-02-01 14:37 UTC, Thomas-Ulrich commented on src/input/MeshAttributes.cpp
> +       child = child->NextSiblingElement("velocityAwareMeshing")) {
Change to:
```
child = child->NextSiblingElement(name)) {
```

2022-02-02 10:07 UTC, krenzland commented on src/input/EasiMeshSize.cpp
> +    // Note: Does not work on discrete regions!
Absolutely no idea. But according to the documentation, it doesn't work on them.

2022-02-02 10:10 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +    // Note: Does not work on discrete regions!
ok. in any case, it works as far as I tested

2022-02-02 16:04 UTC, Thomas-Ulrich requested changes
Nice add-ons!

2022-02-02 16:04 UTC, Thomas-Ulrich commented on src/input/MeshAttributes.cpp
> +         child = child->NextSiblingElement(name)) {
name -> VelocityRefinementCuboid

2022-02-02 16:04 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.h
> +  ;
remove?

2022-02-02 16:04 UTC, Thomas-Ulrich commented on XmlExample/meshAttributes.xml
> +                              extentX="100" extentY="100" extentZ="100" />
consider changing to halfSizeX, Y and Z.

2022-02-02 16:04 UTC, Thomas-Ulrich commented on src/input/EasiMeshSize.cpp
> +  if (material.mu < 10e-14) {
Good idea!

2022-02-02 16:04 UTC, Thomas-Ulrich commented on src/input/MeshAttributes.h
> +  std::array<double, 3> extent;
halfSize

2022-02-03 17:10 UTC, krenzland commented
I've tested it and found an embarssing bug (now fixed). Seems to work!
Setup that I've used for testing: https://syncandshare.lrz.de/getlink/fiY9NKRxjehN4WVkJakwPLiT/mesh_velocity_aware.zip
(Varying material is fun, just make sure they're > 0, otherwise you get very strange results.)

@Thomas-Ulrich Thanks for the comments, I'll address them tomorrow :)

2022-02-04 09:09 UTC, krenzland commented
Reviews addressed. Note that you now need to change extent to halfSize the example that I've linked above. Resulting mesh looks like this:
![image](https://user-images.githubusercontent.com/1886744/152502272-4c9abe89-b585-4168-b790-350569eb1860.png)

2022-02-04 09:32 UTC, Thomas-Ulrich approved these changes

2022-02-04 09:32 UTC, Thomas-Ulrich commented on src/input/MeshAttributes.cpp
> +    logInfo() << "Activating velocity aware meshing, using" << elementsPerWaveLength
could you change that to logInfo(PMU_rank()) ?

2022-02-04 09:32 UTC, Thomas-Ulrich commented on src/input/MeshAttributes.cpp
> +      logInfo() << "Adding velocity aware refinement region targeting" << targetedFrequency
logInfo(PMU_rank())

2022-02-04 09:32 UTC, Thomas-Ulrich commented on src/input/SimModSuite.h
> +      logInfo() << "Enabling velocity aware meshing";
logInfo(PMU_rank())

2022-02-04 10:35 UTC, merged