Thomas/rotate velocity aware box
SeisSol/PUMGen pull request #44
Opened 2022-03-10 16:57 UTC by Thomas-Ulrich

I've added the function suggested by Bo with the option `rotationZAnticlockwiseFromX`. 
Let me know what you think.

2022-03-10 20:04 UTC, Thomas-Ulrich commented
Input file:
```
<freeSurface>9</freeSurface>
<dynamicRupture>8</dynamicRupture>
<absorbing>10,11,12,13,15</absorbing>
<surfaceMSize value="200">8</surfaceMSize>
<area_AspectRatio value="6"/>
<vol_AspectRatio value="12"/>
<SurfaceMeshing SmoothingLevel="1" SmoothingType="Gradient" DiscreteAngle="15.0" Snap="0"></SurfaceMeshing>
<VolumeMeshing  SmoothingLevel="1" SmoothingType="Gradient" SetOptimisation="1"></VolumeMeshing>
<gradation value="0.3"/>
<VelocityAwareMeshing easiFile="RFV_rhomulambda.yaml" elementsPerWaveLength="4">
    <VelocityRefinementCuboid frequency="0.5" centerX="0" centerY="0" centerZ="-15e3"
                              halfSizeX="40e3" halfSizeY="15e3" halfSizeZ="15e3" bypassFindRegionAndUseGroup="1" rotationZAnticlockwiseFromX="30.0"/>
    <VelocityRefinementCuboid frequency="0.25" centerX="0" centerY="0" centerZ="-15e3"
                              halfSizeX="40e10" halfSizeY="15e10" halfSizeZ="15e10" bypassFindRegionAndUseGroup="1"/>
</VelocityAwareMeshing>
````
associated log:
```
Thu Mar 10 20:53:42, Info:  Using SimModSuite
Thu Mar 10 20:53:42, Info:  Loading model
Thu Mar 10 20:53:52, Info:  Extracting cases
Thu Mar 10 20:53:52, Info:  surface smoothing option: surfaceSmoothingLevel surfaceSmoothingType surfaceFaceRotationLimit Snap 1   1   15   0
Thu Mar 10 20:53:52, Info:  volume smoothing option: volumeSmoothingLevel volumeSmoothingType 1   1
Thu Mar 10 20:53:52, Info:  Activating velocity aware meshing, using 4 elements per wavelength and easi file RFV_rhomulambda.yaml
Thu Mar 10 20:53:52, Info:  Adding velocity aware refinement region targeting 0.5 Hz, centered at x = 0 y= 0 z= -15000 with half sizes x = 40000 y = 15000 z = 15000
Thu Mar 10 20:53:52, Info:  rotated around z axis by  30 degree(s) counterclockwise from x axis.
Thu Mar 10 20:53:52, Info:  bypass findRegion and use group = 1
Thu Mar 10 20:53:52, Info:  Adding velocity aware refinement region targeting 0.25 Hz, centered at x = 0 y= 0 z= -15000 with half sizes x = 4e+11 y = 1.5e+11 z = 1.5e+11
Thu Mar 10 20:53:52, Info:  bypass findRegion and use group = 1
Thu Mar 10 20:53:52, Info:  Setting cases
Thu Mar 10 20:53:52, Info:  faceBound[ 9 ] = 1
Thu Mar 10 20:53:52, Info:  faceBound[ 8 ] = 3
Thu Mar 10 20:53:52, Info:  faceBound[ 10 ] = 5
Thu Mar 10 20:53:52, Info:  faceBound[ 11 ] = 5
Thu Mar 10 20:53:52, Info:  faceBound[ 12 ] = 5
Thu Mar 10 20:53:52, Info:  faceBound[ 13 ] = 5
Thu Mar 10 20:53:52, Info:  faceBound[ 15 ] = 5
Thu Mar 10 20:53:52, Info:  face id: 8 , MSize = 200
Thu Mar 10 20:53:52, Info:  Enabling velocity aware meshing
Thu Mar 10 20:53:52, Info:  Gradation rate = 0.3
Thu Mar 10 20:53:52, Info:  Target equivolume AspectRatio = 12
Thu Mar 10 20:53:52, Info:  Target equiarea AspectRatio = 6
Thu Mar 10 20:53:52, Info:  Starting the surface mesher
Thu Mar 10 20:53:52, Info:  Progress: Surface Meshing
Thu Mar 10 20:54:49, Info:  Progress: Adapting Mesh
Thu Mar 10 20:56:21, Info:  Progress: Adapting Mesh
Thu Mar 10 20:56:29, Info:  Progress: Surface Mesh Improver
Thu Mar 10 20:56:29, Info:  Progress: Surface Mesh Improvement , 0 / 2
Thu Mar 10 20:56:29, Info:  Progress: Surface Mesh Improvement , 1 / 2
(...)
```
generated mesh (view from above):
![rotateVelocityAware](https://user-images.githubusercontent.com/13536910/157745223-bc2bf797-def0-47e4-b328-4e72b2fd9b23.png)

2022-03-31 08:53 UTC, krenzland requested changes
Looks great, found just one small thing

2022-03-31 08:53 UTC, krenzland commented on src/input/MeshAttributes.cpp
> +      if (abs(cuboid.rotationZ) > 0.0) {
Should be std::abs

2022-03-31 08:54 UTC, krenzland commented on src/input/MeshAttributes.cpp
> +      if (abs(cuboid.rotationZ) > 0.0) {
See here for reasoning: https://stackoverflow.com/a/21393170
Using abs can lead to compatibility problems

2022-03-31 09:07 UTC, krenzland approved these changes
Thanks!

2022-03-31 09:13 UTC, merged